import Head from "next/head";

// components
import Form from "../src/components/form";

export default function Home() {
  return (
    <>
      <Head>
        <title>Welcome!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;500;700;900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main>
        <div className="splash-page">
          <h1>Welcome.</h1>
          <h2>Tell us a little bit about yourself.</h2>
        </div>
        <Form />
      </main>
    </>
  );
}
